Fix underlinking (-lm) of libgegl.so
When linking with ld.gold the builds fails due to underlinking of libgegl.so
./.libs/libgegl-0.3.so: error: undefined reference to 'tanhf'

Gnome-Bugs: https://bugzilla.gnome.org/show_bug.cgi?id=759065

Signed-off-by: Justin Lecher <jlec@gentoo.org>